CREATE SCHEMA IF NOT EXISTS `bd_design`;

USE bd_design;

CREATE TABLE IF NOT EXISTS Cliente(
    id_cliente INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    telefone VARCHAR(11) NOT NULL,
    cep VARCHAR(12) NOT NULL,
    numero INT NOT NULL
);
